name: superfrog
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.2.0
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.4
  go_router: ^14.1.4
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  flutter_bloc: ^8.1.5
  moon_design: ^0.57.0
  easy_localization: ^3.0.7
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  cross_file: ^0.3.4+1
  path_provider: ^2.1.3
  mime_type: ^1.0.0
  universal_html: ^2.2.4
  path: ^1.9.0
  cloudflare_turnstile: ^0.4.0
  get_it: ^7.7.0
  package_info_plus: ^8.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
#  flutter_launcher_icons: ^0.13.1

#flutter_launcher_icons:
#  image_path: "assets/images/logo.png"
#  android: true
#  ios: true 
#  web:
#    generate: true

flutter:  
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  