name: superfrog
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  supabase_flutter: ^2.3.1
  go_router: ^13.1.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.6
  flutter_bloc: ^8.1.3
  moon_design: ^0.53.0
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  multi_split_view: ^2.4.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  cross_file: ^0.3.4+1
  path_provider: ^2.1.3
  mime_type: ^1.0.0
  universal_html: ^2.2.4
  path: ^1.9.0
  cloudflare_turnstile: ^0.2.1
  file_picker: ^8.0.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:  
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  