name: superfrog
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  supabase_flutter: ^2.3.1
  go_router: ^13.1.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.6
  flutter_bloc: ^8.1.3
  moon_design: ^0.47.0
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.3
  flutter_svg: ^2.0.9
  cross_file: ^0.3.3+8
  file_picker: ^6.1.1
  mime: ^1.0.5
  tus_client_dart:
    git:
      url: https://github.com/martinralfreindl/tus_client.git
      ref: master
  uuid: ^4.3.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:  
  uses-material-design: true

  assets:
    - assets/locales/
    - assets/images/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  