name: Build App

on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: false
      upload-tag:
        type: string
        default: "actions"

env:
  FLUTTER_VERSION: "3.19.6"
  ANDROID_SIGNING_KEY: "${{ secrets.ANDROID_SIGNING_KEY }}"


jobs:
  build-for-Android:
    name: build android apk ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              arch: aarch64,
              target: android-arm64,
              os: ubuntu-latest,
            }
          - {
              arch: armv7,
              target: android-arm,
              os: ubuntu-latest
            }
          - {
              arch: x86_64,
              target: android-x64,
              os: ubuntu-latest
            }
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
        
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: ${{ env.FLUTTER_VERSION }}
    
    - name: Prepare for build
      run: |
        flutter pub get
        dart run build_runner build --delete-conflicting-outputs
        
    - run: flutter analyze
    
    - name: Build unsigned apk
      run: |
        sed -i "s/signingConfigs.release/signingConfigs.debug/g" ./android/app/build.gradle
        flutter build apk --release --target-platform ${{ matrix.job.target }}

    - name: Sign release Apk
      uses: r0adkll/sign-android-release@v1
      if: env.ANDROID_SIGNING_KEY != null
      id: sign_app
      with:
        releaseDirectory: build/app/outputs/flutter-apk/
        signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
        alias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}