name: Flutter CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - ".vscode/**"
      - "docs/**" 
      - "README.md"

jobs:
  run-check:
    uses: ./.github/workflows/flutter-analysis.yml
  run-ci:
    needs: run-check
    uses: ./.github/workflows/build.yml